[package]
name = "use-mqtt-in-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "my_mqtt_lib"
path = "src/lib.rs"

[dependencies]
paho-mqtt = "0.11"
dotenv = "0.15.0"
sysinfo = "0.23.12"
chrono = "0.4"
